plugins:
  - serverless-offline

service: tyvm

provider:
  name: aws
  runtime: nodejs6.10

functions:
  server:
    handler: server/build/server.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
